# Generated by Django 4.2.2 on 2023-06-28 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cod_activacion', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.carrito')),
                ('id_juego', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(max_length=50)),
                ('papellido', models.CharField(max_length=50)),
                ('sapellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('usrdjango', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente'),
        ),
    ]
