# Generated by Django 4.2.2 on 2023-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
